apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 6ixbit/v2-personal-website-ui:latest
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
spec: 
    type: NodePort
    selector: 
      app: frontend
    ports: 
      - nodePort: 30501
        port: 8080
        targetPort: 8080
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  selector:
    matchLabels:
      app: backend-api
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: 6ixbit/v2-personal-website-server:latest
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: backend-api-service
spec:
    type: NodePort
    selector:
      app: backend-api
    ports:
      - nodePort: 30500
        port: 8080
        targetPort: 8080