version: '3'

services: 
    backend:
        image: 6ixbit/v2-personal-website-server:latest
        ports: 
            - 8080:8080
        restart: always
        environment:
            - "GITHUB_URL=https://api.github.com/users/6ixbit/repos?direction=desc"
            - "GITHUB_USERNAME=6ixBit"

    frontend:
        build: .
        ports: 
            - 9000:8080
        restart: always
        depends_on: 
          - backend